// ============================================================
// The jobsync — Production Taxonomy (Clean Version)
// Departments, Industries, Role Categories
// ============================================================

export const DEPARTMENTS = [
  "Engineering - Software & QA",
  "Sales & Business Development",
  "Customer Success, Service & Operations",
  "Finance & Accounting",
  "Production, Manufacturing & Engineering",
  "BFSI, Investments & Trading",
  "Human Resources",
  "IT & Information Security",
  "Marketing & Communication",
  "Data Science & Analytics",
  "Consulting",
  "Healthcare & Life Sciences",
  "Administration & Facilities",
  "Project & Program Management",
  "Procurement & Supply Chain",
  "Engineering - Hardware & Networks",
  "Construction & Site Engineering",
  "Teaching & Training",
  "UX, Design & Architecture",
  "Research & Development",
  "Quality Assurance",
  "Food, Beverage & Hospitality",
  "Legal & Regulatory",
  "Product Management",
  "Content, Editorial & Journalism",
  "Environment, Health & Safety",
  "Risk Management & Compliance",
  "Merchandising, Retail & eCommerce",
  "Strategic & Top Management",
  "Media Production & Entertainment",
  "Security Services",
  "Sports, Fitness & Personal Care",
  "CSR & Social Service",
  "Aviation & Aerospace",
  "Energy & Mining",
  "Shipping & Maritime",
] as const;

export const INDUSTRIES = [
  // IT & Technology
  "IT Services & Consulting",
  "Software Product",
  "Internet",
  "Hardware & Networking",
  "Electronics Manufacturing",
  "Electronic Components & Semiconductors",
  "Emerging Technologies",
  // BPM / Analytics
  "BPM / BPO",
  "Analytics / KPO / Research",
  // Infrastructure
  "Real Estate",
  "Engineering & Construction",
  "Power",
  "Courier & Logistics",
  "Oil & Gas",
  "Water Treatment & Waste Management",
  "Aviation",
  "Ports & Shipping",
  "Urban Transport",
  "Railways",
  // BFSI
  "Banking",
  "Insurance",
  "Financial Services",
  "NBFC",
  "FinTech & Payments",
  "Investment Banking / Venture Capital / Private Equity",
  // Healthcare
  "Medical Services & Hospitals",
  "Pharmaceutical & Life Sciences",
  "Medical Devices & Equipment",
  "Biotechnology",
  "Clinical Research / Contract Research",
  // Professional Services
  "Recruitment & Staffing",
  "Accounting & Auditing",
  "Management Consulting",
  "Architecture & Interior Design",
  "Facility Management Services",
  "Legal Services",
  "Design Services",
  "Law Enforcement & Security Services",
  "Content Development & Language Services",
  // Education
  "Education & Training",
  "E-Learning & EdTech",
  // Manufacturing
  "Industrial Equipment & Machinery",
  "Automobile",
  "Auto Components",
  "Building Materials",
  "Defence & Aerospace",
  "Chemicals",
  "Industrial Automation",
  "Electrical Equipment",
  "Iron & Steel",
  "Petrochemicals, Plastics & Rubber",
  "Packaging & Containers",
  "Metals & Mining",
  "Fertilizers, Pesticides & Agrochemicals",
  "Pulp & Paper",
  // Media
  "Advertising & Marketing",
  "Telecom & ISP",
  "Printing & Publishing",
  "Film, Music & Entertainment",
  "Events & Live Entertainment",
  "TV & Radio",
  "Gaming",
  "Sports, Leisure & Recreation",
  "Animation & VFX",
  // Consumer
  "Retail",
  "Hotels & Restaurants",
  "FMCG",
  "Travel & Tourism",
  "Consumer Electronics & Appliances",
  "Textile & Apparel",
  "Food Processing",
  "Beverage",
  "Fitness & Wellness",
  "Gems & Jewellery",
  "Furniture & Furnishing",
  "Beauty & Personal Care",
  "Leather",
  // Others
  "NGO / Social Services / Industry Associations",
  "Agriculture / Forestry / Fishing",
  "Import & Export",
  "Government / Public Administration",
  "Miscellaneous",
] as const;

export const ROLE_CATEGORIES = [
  "Software Development",
  "Retail & B2C Sales",
  "BD / Pre Sales",
  "Enterprise & B2B Sales",
  "Voice / Blended",
  "Non Voice",
  "Quality Assurance & Testing",
  "Accounting & Taxation",
  "DBA / Data Warehousing",
  "IT Consulting",
  "Finance",
  "Engineering",
  "Construction Engineering",
  "Recruitment & Talent Acquisition",
  "Operations, Maintenance & Support",
  "Customer Success, Service & Operations",
  "Business Intelligence & Analytics",
  "Operations",
  "Facility Management",
  "IT Network",
  "IT Infrastructure Services",
  "IT Support",
  "IT Security",
  "Administration",
  "Data Science & Machine Learning",
  "Digital Marketing",
  "Marketing",
  "Customer Success",
  "Sales Support & Operations",
  "Procurement & Purchase",
  "Finance & Accounting",
  "General Insurance",
  "Engineering & Manufacturing",
  "Technology / IT",
  "SCM & Logistics",
  "Architecture & Interior Design",
  "Lending",
  "Life Insurance",
  "Production & Manufacturing",
  "Management Consulting",
  "Health Informatics",
  "Trading, Asset & Wealth Management",
  "Operations Support",
  "Hardware",
  "After Sales Service & Repair",
  "Treasury",
  "Back Office",
  "Advertising & Creative",
  "Management",
  "Corporate Communication",
  "Product Management - Technology",
  "Product Management - Business",
  "Business Process Quality",
  "Corporate Training",
  "Audit & Control",
  "Content Management",
  "Stores & Material Management",
  "UI / UX Design",
  "Front Office & Guest Services",
  "Kitchen & Food Production",
  "Nursing",
  "Doctor",
  "Imaging & Diagnostics",
  "Legal Operations",
  "Risk Management & Compliance",
  "Service Delivery",
  "Retail Store Operations",
  "Employee Relations",
  "Top Management",
  "Corporate Affairs",
  "Compensation & Benefits",
  "Community Health & Safety",
  "Occupational Health & Safety",
  "Strategic Management",
  "Security Officer",
  "Editing",
  "Journalism",
  "Tourism Services",
  "Market Research & Insights",
  "Payroll & Transactions",
  "Import & Export",
  "eCommerce Operations",
  "Housekeeping & Laundry",
  "Preschool & Primary Education",
  "Procurement & Supply Chain",
  "Telecom",
  "Surveying",
  "Merchandising & Planning",
  "Security & Fraud",
  "Fashion & Accessories",
  "Assessment & Advisory",
  "Events & Banquet",
  "Life Skills / ECA Teacher",
  "CSR & Sustainability",
  "Artists",
  "Beauty & Personal Care",
  "Operations & Strategy",
  "Health & Fitness",
  "Recruitment Marketing & Branding",
  "Category Management & Operations",
  "Business",
  "Merchandising, Retail & eCommerce",
  "Flight & Airport Operations",
  "Social & Public Service",
  "Animation & Effects",
  "Mining",
  "Shipping & Maritime",
  "Treasury & Forex",
  "Aviation Engineering",
  "Airline Services",
  "Power Generation",
  "Direction",
  "Port & Maritime Operations",
  "Power Supply & Distribution",
  "Shipping Deck",
  "Sports Staff & Management",
  "Pilot",
  "Sound, Light & Technical Support",
  "Shipping Engineering & Technical",
  "Upstream",
  "Midstream",
  "Downstream",
  "Crime & Arbitration",
] as const;

export const SALARY_RANGES = [
  '0 - 2 LPA',
  '2 - 5 LPA',
  '5 - 8 LPA',
  '8 - 12 LPA',
  '12 - 18 LPA',
  '18 - 25 LPA',
  '25+ LPA',
] as const;
